name: Create Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Build Electron App for Linux
        run: npm run build:linux

      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v4
        with:
          name: markdoom-linux
          path: ./dist/*.AppImage  # Adjust this path to the Linux output

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Build Electron App for Windows
        run: npm run build:win

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: markdoom-windows
          path: ./dist/*.exe  # Adjust this path to the Windows output

  release:
    needs: [build-linux, build-windows]
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Linux Artifact
        uses: actions/download-artifact@v4
        with:
          name: markdoom-linux
          path: ./dist/linux

      - name: Download Windows Artifact
        uses: actions/download-artifact@v4
        with:
          name: markdoom-windows
          path: ./dist/windows

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${tag#v}" \
              --generate-notes \
              ./dist/linux/*.AppImage#"markdoom-linux-${tag#v}.AppImage" \
              ./dist/windows/*.exe#"markdoom-windows-${tag#v}.exe"
