name: Create Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Build Electron App for Linux
        run: npm run build:linux

      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v4
        with:
          name: markdoom-linux
          path: dist/*.AppImage

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Build Electron App for Windows
        run: npm run build:win

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: markdoom-windows
          path: dist/*.exe

  release:
    needs: [build-linux, build-windows]
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Linux Artifact
        uses: actions/download-artifact@v4
        with:
          name: markdoom-linux
          path: dist/linux

      - name: Download Windows Artifact
        uses: actions/download-artifact@v4
        with:
          name: markdoom-windows
          path: dist/windows

      - name: Display structure of downloaded files
        run: ls -R
        working-directory: dist

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          linux_file=$(find dist/linux -name "*.AppImage" -print -quit)
          windows_file=$(find dist/windows -name "*.exe" -print -quit)
          
          if [ -z "$linux_file" ]; then
            echo "Linux AppImage not found"
            exit 1
          fi
          
          if [ -z "$windows_file" ]; then
            echo "Windows executable not found"
            exit 1
          fi
          
          gh release create "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${tag#v}" \
              --generate-notes \
              "$linux_file#markdoom-linux-${tag#v}.AppImage" \
              "$windows_file#markdoom-windows-${tag#v}.exe"