name: Build Electron App for Windows and Linux

on:
  push:
    branches:
      - main  # Adjust if you use a different default branch

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Updated to v4

      - name: Setup Node.js
        uses: actions/setup-node@v4  # Updated to v4
        with:
          node-version: '20.x'  # Explicitly set to Node.js 20

      - name: Install dependencies
        run: npm install

      - name: Build Electron App
        run: npm run build

      - name: Package Electron App
        run: |
          if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
            npm run build:linux   # For Linux
          else
            npm run build:win     # For Windows
          fi

      - name: Upload Artifact
        uses: actions/upload-artifact@v4  # Updated to v4
        with:
          name: electron-app-${{ matrix.os }}
          path: |
            ./dist/*.AppImage  # For Linux
            ./dist/*.exe       # For Windows
